# Generated by Django 4.2 on 2025-02-13 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip',
            name='ciutat',
            field=models.CharField(default='ninguna parte', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equip',
            name='estadi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbol.jugador'),
        ),
        migrations.AlterField(
            model_name='event',
            name='partit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbol.partit'),
        ),
    ]
